version: '3'
services:
  apache_php:
    image: my-php-apache
    ports:
      - "8082:80"
    volumes:
      - ./codi_php:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
